#!/usr/bin/env bash

cd $LLVM_DIRECTORY
git checkout llvmorg-15.0.3
rm -rf $LLVM_BUILD_DIRECTORY
mkdir -p $LLVM_BUILD_DIRECTORY
cd $LLVM_BUILD_DIRECTORY
cmake ../llvm -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
  # Uncomment to build examples
  # -DLLVM_BUILD_EXAMPLES=ON \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;mlir" \
  # Uncomment for a faster build on Linux
  # -DLLVM_ENABLE_LLD=ON \
  -DLLVM_TARGETS_TO_BUILD="AArch64;X86;NVPTX;AMDGPU"
ninja
cd -
