apiVersion: v1
kind: ServiceAccount
metadata:
  name: memory
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: memory
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: memory
subjects:
- kind: ServiceAccount
  name: memory
roleRef:
  kind: Role
  name: memory
  apiGroup: rbac.authorization.k8s.io
